<?php
/**
 * @file
 * Laravel Example.
 */

/**
 * Implements hook_menu().
 */
function illuminate_example_menu() {

  $items['illuminate-example'] = array(
    'title' => 'Laravel Example',
    'page callback' => 'illuminate_example_page',
    'page arguments' => array() ,
    'access arguments' => array(
      'access content'
    ) ,
  );

  $items['illuminate-example/%'] = array(
    'title' => 'Laravel Example',
    'page callback' => 'illuminate_example_detail_page',
    'page arguments' => array(1) ,
    'access arguments' => array(
      'access content'
    ) ,
  );

  return $items;
}

function illuminate_example_page(){
  illuminate_example_drupalconfig();

  return "OK";
}

function illuminate_example_detail_page($group) {
  return "OK";
}

function illuminate_example_cache(){

  $cachedata = Cache::remember('illuminate_example_cache', 1, function(){
      return "Now is:" . date("Y-m-d h:i:s");
  });

  dpm($cachedata);
}

function illuminate_example_yamlconfig(){
  $config = YAML::load('illuminate_example');

  if($con_vars = $config->get('name')){
    dpm($con_vars);
  }

}

function illuminate_example_drupalconfig(){
  $output = array();
  $output[] = "Put value for illuminate_example::key-1";
  DrupalConfig::put("illuminate_example", "key-1", "value-1");

  $output[] = ("Put value for illuminate_example::key-2");
  DrupalConfig::put("illuminate_example", "key-2", "value-2");

  $output[] = ("illuminate_example::key-1::" . DrupalConfig::get("illuminate_example", "key-1"));
  $output[] = ("illuminate_example::key-2::" . DrupalConfig::get("illuminate_example", "key-2"));

  $output[] = ("Remove illuminate_example::key-1");
  DrupalConfig::forget("illuminate_example", "key-1");
  $output[] = ("illuminate_example::key-1::" . DrupalConfig::get("illuminate_example", "key-1"));
  $output[] = ("All illuminate_example keys");
  $output[] = (DrupalConfig::all("illuminate_example"));

  $output[] = ("Remove all illuminate_example keys");
  DrupalConfig::flush("illuminate_example");
  $output[] = ("Check illuminate_example keys::");

  $output[] = (DrupalConfig::all("illuminate_example"));

  dpm($output);
}
